# Based in ruby-26-rhel7:latest from registry.access.redhat.com
FROM registry.redhat.io/rhscl/ruby-26-rhel7:latest

USER 0

# Dependencies
RUN yum -y install \
    tar \
    gzip \
    bzip2 \
    openssl \
    curl \
    openssl-devel \
    readline-devel \
    libevent-devel \
    libyaml-devel \
    zlib-devel \
  && yum clean all

# OTS
RUN mkdir -p /var/log/onetime /var/run/onetime /var/lib/onetime /etc/onetime /opt/app-root/src
COPY . /opt/app-root/src
RUN cd /opt/app-root/src \
  && bundle install --frozen --deployment --without=dev \
  && gem update \
  && bin/ots init \
  && cp -R etc/* /etc/onetime

# Entrypoint
COPY entrypoint.sh /entrypoint.sh

# Permissions
RUN chown -R 0 /entrypoint.sh /var/log/onetime /var/run/onetime /var/lib/onetime /etc/onetime /opt/app-root/src \
  && chmod -R g=u /entrypoint.sh /var/log/onetime /var/run/onetime /var/lib/onetime /etc/onetime /opt/app-root/src \
  && chmod -R 770 /entrypoint.sh /opt/app-root/src/bin

EXPOSE 7143
USER 1001
WORKDIR /opt/app-root/src

ENTRYPOINT ["/entrypoint.sh"]
